admin:
  username: ${ADMIN_USER}
  password: ${ADMIN_PASS}
mqtt:
  client-id: ${MQTT_CLIENT_ID:-backend}
  topic: ${MQTT_TOPIC:-hydrohomie}
  url: ${MQTT_URL}
spring:
  #liquibase:
  #  change-log: classpath:liquibase/changelog_master.yaml
  #  url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
  #  user: ${DB_USER}
  #  password: ${DB_PASS}
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
